/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kkllffaa_meteorutils_NativeMethods */

#ifndef _Included_com_kkllffaa_meteorutils_NativeMethods
#define _Included_com_kkllffaa_meteorutils_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kkllffaa_meteorutils_NativeMethods
 * Method:    ble
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_kkllffaa_meteorutils_NativeMethods_ble
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_kkllffaa_meteorutils_NativeMethods
 * Method:    ff
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kkllffaa_meteorutils_NativeMethods_ff
  (JNIEnv *, jclass);

/*
 * Class:     com_kkllffaa_meteorutils_NativeMethods
 * Method:    addd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_kkllffaa_meteorutils_NativeMethods_addd
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
